version: '2'

volumes:
    d2test:
services:
  detectron2:
    build: .
    restart: always
    volumes:
      - d2test:/home/d2test
    environment:
#      - SEGMENTATION_MODEL=COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
      - SEGMENTATION_MODEL=COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml
#      - SEGMENTATION_MODEL=Cityscapes/mask_rcnn_R_50_FPN.yaml
      - FLASK_DEBUG=True
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    ports:
      - 5000:5000